import type { Architecture, Subnet } from "./model.ts";

export function renderTerraform(arch: Architecture): string {
  const lines: string[] = [];

  lines.push(
    "# Generated by p01-java-aws-3tier. Apply only into a sandbox account.",
    "",
    'terraform {',
    "  required_providers {",
    '    aws = {',
    '      source  = "hashicorp/aws"',
    '      version = "~> 5.0"',
    "    }",
    "  }",
    "}",
    "",
    'variable "env" {',
    '  default = "dev"',
    "}",
    "",
  );

  lines.push(
    `resource "aws_vpc" "main" {`,
    `  cidr_block           = "${arch.vpcCidr}"`,
    `  enable_dns_support   = true`,
    `  enable_dns_hostnames = true`,
    "",
    "  tags = {",
    `    Name = "${arch.name}"`,
    "  }",
    "}",
    "",
    `data "aws_availability_zones" "available" {`,
    "  state = \"available\"",
    "}",
    "",
  );

  for (const subnet of arch.subnets) {
    lines.push(
      `resource "aws_subnet" "${subnetResourceName(subnet)}" {`,
      "  vpc_id                  = aws_vpc.main.id",
      `  cidr_block              = "${subnet.cidr}"`,
      `  availability_zone       = "${subnet.availabilityZone}"`,
      `  map_public_ip_on_launch = ${subnet.tier === "web" ? "true" : "false"}`,
      "",
      "  tags = {",
      `    Name = "${arch.name}-${subnet.tier}-${subnet.index}"`,
      "  }",
      "}",
      "",
    );
  }

  lines.push(
    `resource "aws_internet_gateway" "main" {`,
    "  vpc_id = aws_vpc.main.id",
    "}",
    "",
    `resource "aws_route_table" "public" {`,
    "  vpc_id = aws_vpc.main.id",
    "",
    "  route {",
    '    cidr_block = "0.0.0.0/0"',
    "    gateway_id = aws_internet_gateway.main.id",
    "  }",
    "}",
    "",
  );

  const pubSubnets = arch.subnets.filter((s) => s.tier === "web");

  for (const subnet of pubSubnets) {
    lines.push(
      `resource "aws_route_table_association" "web_${subnet.index}" {`,
      `  subnet_id      = aws_subnet.${subnetResourceName(subnet)}.id`,
      "  route_table_id = aws_route_table.public.id",
      "}",
      "",
    );
  }

  for (const [tier, sg] of Object.entries(arch.securityGroups)) {
    lines.push(
      `resource "aws_security_group" "${tier}" {`,
      `  name        = "${sg.name}"`,
      `  description = "${sg.description}"`,
      "  vpc_id      = aws_vpc.main.id",
      "",
    );

    for (const rule of arch.ingressRules[tier as keyof typeof arch.ingressRules]) {
      lines.push("  ingress {");
      lines.push(`    from_port   = ${rule.fromPort}`);
      lines.push(`    to_port     = ${rule.toPort}`);
      lines.push(`    protocol    = "${rule.protocol}"`);
      if (rule.sourceCidr) {
        lines.push(`    cidr_blocks = ["${rule.sourceCidr}"]`);
      }
      if (rule.sourceGroup) {
        lines.push("    security_groups = [");
        lines.push(`      aws_security_group.${rule.sourceGroup}.id,`);
        lines.push("    ]");
      }
      lines.push("  }");
      lines.push("");
    }

    lines.push("  egress {");
    lines.push("    from_port   = 0");
    lines.push("    to_port     = 0");
    lines.push('    protocol    = "-1"');
    lines.push('    cidr_blocks = ["0.0.0.0/0"]');
    lines.push("  }");
    lines.push("}");
    lines.push("");
  }

  const webTier = arch.subnets.filter((s) => s.tier === "web");
  for (let i = 0; i < webTier.length; i += 1) {
    lines.push(
      `resource "aws_instance" "web_${i}" {`,
      "  ami                         = data.aws_ami.amazon_linux.id",
      "  instance_type               = \"t3.micro\"",
      `  subnet_id                   = aws_subnet.${subnetResourceName(webTier[i]!)}.id`,
      "  vpc_security_group_ids      = [aws_security_group.web.id]",
      "  associate_public_ip_address = true",
      "",
      "  user_data = <<-EOT",
      "    #!/bin/bash",
      "    yum install -y httpd",
      "    systemctl enable --now httpd",
      "    echo ok > /var/www/html/index.html",
      "  EOT",
      "",
      "  tags = {",
      `    Name = "${arch.name}-web-${i}"`,
      "  }",
      "}",
      "",
    );
  }

  const appTier = arch.subnets.filter((s) => s.tier === "app");
  for (let i = 0; i < appTier.length; i += 1) {
    lines.push(
      `resource "aws_instance" "app_${i}" {`,
      "  ami                    = data.aws_ami.amazon_linux.id",
      "  instance_type          = \"t3.micro\"",
      `  subnet_id              = aws_subnet.${subnetResourceName(appTier[i]!)}.id`,
      "  vpc_security_group_ids = [aws_security_group.app.id]",
      "",
      "  tags = {",
      `    Name = "${arch.name}-app-${i}"`,
      "  }",
      "}",
      "",
    );
  }

  lines.push(
    'resource "aws_db_subnet_group" "main" {',
    "  name = \"main\"",
    "  subnet_ids = [",
    ...arch.subnets
      .filter((s) => s.tier === "db")
      .map((s) => `    aws_subnet.${subnetResourceName(s)}.id,`),
    "  ]",
    "}",
    "",
    `resource "aws_db_instance" "main" {`,
    "  engine                 = \"postgres\"",
    "  engine_version         = \"15.4\"",
    "  instance_class         = \"db.t3.micro\"",
    "  allocated_storage      = 20",
    "  db_subnet_group_name   = aws_db_subnet_group.main.name",
    "  vpc_security_group_ids = [aws_security_group.db.id]",
    "  skip_final_snapshot    = true",
    "",
    "  tags = {",
    `    Name = "${arch.name}-db"`,
    "  }",
    "}",
    "",
    `data "aws_ami" "amazon_linux" {`,
    "  most_recent = true",
    "",
    "  filter {",
    '    name   = "name"',
    '    values = ["al2023-ami-2023.*-x86_64"]',
    "  }",
    "",
    "  owners = [\"137112412989\"]",
    "}",
    "",
  );

  return lines.join("\n").trimEnd() + "\n";
}

function subnetResourceName(subnet: Subnet): string {
  return `${subnet.tier}_${subnet.index}`;
}