import type { AzurePipelineConfig } from "./model.ts";

export function renderMainTf(config: AzurePipelineConfig): string {
  return `# Generated by src/azurerm.ts for ${config.workspace}/${config.environment}.
terraform {
  required_version = ">= ${config.terraformVersion}"
  backend "azurerm" {
    key = "${'${var.workspace}'}/infra/${'${var.scope}'}.tfstate"
  }
}

variable "scope" {
  default = "global"
}

variable "workspace" {
  default = "${config.workspace}"
}

provider "azurerm" {
  features {}
  # auth: OIDC federated credential bound to a service connection, no secrets.
}

resource "azurerm_resource_group" "this" {
  name     = "${config.resourceGroup}"
  location = "${config.location}"
}

resource "azurerm_storage_account" "state" {
  name                     = "${config.storageAccount}"
  resource_group_name      = azurerm_resource_group.this.name
  location                 = azurerm_resource_group.this.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  allow_nested_items_to_be_public = false
}

resource "azurerm_storage_container" "state" {
  name                  = "${config.containerName}"
  storage_account_name  = azurerm_storage_account.state.name
  container_access_type = "private"
}

resource "azurerm_virtual_network" "this" {
  name                = "vnet-\${replace(var.workspace, "_", "-")}"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  address_space       = ["10.10.0.0/16"]

  tags = {
    environment = "${config.environment}"
    managed_by  = "terraform"
  }
}
`;
}

export function renderPipeline(config: AzurePipelineConfig): string {
  return `# azure-pipelines.yml rendered by src/azurerm.ts
trigger:
  branches:
    include:
      - main
pr: none

variables:
  - group: terraform-contributor

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Plan
    jobs:
      - job: terraform_plan
        steps:
          - script: |
              terraform init
              terraform workspace select ${config.environment} || terraform workspace new ${config.environment}
              terraform plan -out=tfplan -var scope="infra"
            displayName: terraform init and plan

  - stage: Apply
    condition: succeeded()
    dependsOn: Plan
    environment: ${config.environment}-approval
    jobs:
      - job: terraform_apply
        steps:
          - script: |
              terraform workspace select ${config.environment}
              terraform apply -auto-approve tfplan
            displayName: terraform apply
`;
}

export function renderCheatSheet(config: AzurePipelineConfig): string {
  return `# Azure Terraform cheat sheet (${config.environment})

- State lives in ${config.storageAccount}/${config.containerName}, keyed
  ${config.workspace}/<component>/<scope>.tfstate via src/model.ts:backendKey.
- The ${config.environment}-approval environment in Azure DevOps gates the
  apply stage; contributors never hold a write credential.
- For prod, destroys are refused by src/model.ts:planGate before the apply
  stage even starts.
`;
}