import type { CatalogItem } from "./catalog.ts";

export interface PipelineOptions {
  repoOwner: string;
  repoName: string;
  mainBranch: string;
  auditLevel: string;
}

export function defaultPipeline(): PipelineOptions {
  return {
    repoOwner: "shamanchi",
    repoName: "watch-catalog",
    mainBranch: "main",
    auditLevel: "high",
  };
}

export function renderWorkflow(pipeline: PipelineOptions): string {
  const image = `ghcr.io/${pipeline.repoOwner}/${pipeline.repoName}`;
  return `# DevSecOps workflow for the watch catalog, generated by src/pipeline.ts.
# The workflow never runs a deployment on pull requests; it never embeds
# secrets - anything secret arrives through actions secrets and environment
# protection rules.
name: devsecops

on:
  push:
    branches: [${pipeline.mainBranch}]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run gate
      - run: npm run audit

  sast:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run check

  image-build:
    needs: sast
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build image (no push on PRs)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${image}:RUN_ID
`;
}

export function renderCheatSheet(pipeline: PipelineOptions): string {
  const image = `ghcr.io/${pipeline.repoOwner}/${pipeline.repoName}`;
  return [
    `# DevSecOps practice for this repository`,
    ``,
    `1. Every pull request runs quality, npm audit (high), and the local SAST`,
    `   check (npm run check). Nothing is deployed from a pull request.`,
    `2. The image build job only runs on ${pipeline.mainBranch} pushes and`,
    `   builds (does not push) with an UNIQUE immutable tag.`,
    `3. To deploy, wire the image ${image}:<git-sha> through an environment`,
    `   that requires a human review, matching the release stage of the`,
    `   advanced-cicd pipeline in this portfolio.`,
    `4. Keep at least: lint + tests (npm run gate), dependency audit (npm audit`,
    `   at level ${pipeline.auditLevel}), secret patterns and dangerous calls`,
    `   (src/sast.ts, npm run check), and container build scanning before a`,
    `   production release.`,
  ].join("\n");
}