import type { TfStackConfig } from "./model.ts";

export type ApplyAction = "create" | "update" | "noop" | "destroy";

export interface ApplyDecision {
  action: ApplyAction;
  reasons: string[];
}

export interface ObservedCluster {
  nodesRunning: number;
  version: string | undefined;
  jenkinsDeployed: boolean;
}

export function decideApply(config: TfStackConfig, observed: ObservedCluster): ApplyDecision {
  const reasons: string[] = [];
  if (observed.nodesRunning === 0 && observed.version === undefined) {
    reasons.push("no cluster observed");
    return { action: "create", reasons };
  }
  if (observed.version !== config.clusterVersion) {
    reasons.push(`cluster version ${observed.version} -> ${config.clusterVersion}`);
  }
  if (observed.nodesRunning !== config.nodeCount) {
    reasons.push(`nodes ${observed.nodesRunning} -> ${config.nodeCount}`);
  }
  if (!observed.jenkinsDeployed) {
    reasons.push("helm_release.jenkins missing");
  }
  if (reasons.length === 0) {
    return { action: "noop", reasons: ["state matches configuration"] };
  }
  return { action: config.workspace === "prod" ? "update" : "destroy", reasons };
}

export function braceBalance(tf: string): boolean {
  let balance = 0;
  for (const char of tf) {
    if (char === "{") balance += 1;
    if (char === "}") balance -= 1;
  }
  return balance === 0;
}

export function renderMainTf(config: TfStackConfig): string {
  return `# Generated by src/terraform.ts for ${config.workspace}.
terraform {
  required_version = ">= 1.9"
  backend "s3" {
    bucket   = "tf-${config.workspace}-state"
    key      = "eks/terraform.tfstate"
    region   = "${'${var.region}'}"
    encrypt  = true
  }
}

provider "aws" {
  region = ${'${var.region}'}
}

variable "region" {
  default = "${config.region}"
}

variable "environment" {
  default = "${config.workspace}"
}

variable "vpc_cidr" {
  default = "10.0.0.0/16"
}

data "aws_eks_cluster" "this" {
  name = aws_eks_cluster.this.name
}

resource "aws_eks_cluster" "this" {
  name     = "${config.clusterName}"
  role_arn = aws_iam_role.eks.arn
  version  = "${config.clusterVersion}"

  vpc_config {
    subnet_ids = [aws_subnet.pods_a.id, aws_subnet.pods_b.id]
  }
}

resource "aws_eks_node_group" "this" {
  cluster_name    = aws_eks_cluster.this.name
  node_group_name = "${config.workspace}-nodes"
  node_role_arn   = aws_iam_role.nodes.arn
  instance_types  = ["${config.nodeInstanceType}"]
  disk_size       = ${config.nodeDiskSize}
  scaling_config {
    desired_size = ${config.nodeCount}
    min_size     = ${config.nodeMinSize}
    max_size     = ${config.nodeMaxSize}
  }
  depends_on = [aws_iam_role_policy_attachment.nodes]
}

resource "helm_release" "jenkins" {
  name       = "${config.jenkinsRelease}"
  repository = "https://charts.jenkins.io"
  chart      = "jenkins"
  namespace  = "${config.jenkinsNamespace}"
  create_namespace = true

  set {
    name  = "controller.image"
    value = "jenkins/jenkins:lts-jdk17"
  }
}

resource "aws_subnet" "pods_a" {
  vpc_id            = aws_vpc.this.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 3, 0)
  availability_zone = "${config.region}a"
}

resource "aws_subnet" "pods_b" {
  vpc_id            = aws_vpc.this.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 3, 1)
  availability_zone = "${config.region}b"
}

resource "aws_vpc" "this" {
  cidr_block = var.vpc_cidr
}

# IAM roles omitted from the snippet; controllers attach the AWS managed
# policies by name so no inline policy dumps are ever committed.
`;
}

export function renderOutputsTf(config: TfStackConfig): string {
  return `output "cluster_endpoint" {
  value = aws_eks_cluster.this.endpoint
}

output "cluster_name" {
  value = aws_eks_cluster.this.name
}

output "jenkins_url" {
  value = "https://jenkins.${config.workspace}.example.internal"
}
`;
}

export function renderApplySheet(config: TfStackConfig): string {
  return `# Terraform apply sheet (workspace ${config.workspace})

1. Init and select the workspace:
   terraform init
   terraform workspace select ${config.workspace}

2. Render the plan and review the diff before applying:
   terraform plan -out=tfplan -var region=${config.region}
   terraform show tfplan

3. Apply after the review gate approves the diff:
   terraform apply tfplan

4. After apply, wire kubectl to EKS:
   aws eks update-kubeconfig --region ${config.region} --name ${config.clusterName}

   helm list -n ${config.jenkinsNamespace}
`;
}