export interface PipelinePlan {
  auditLevel: "high";
  image: string;
}

export const DEFAULT_PLAN: PipelinePlan = {
  auditLevel: "high",
  image: "ghcr.io/shamanchi/food-catalog:main",
};

export function renderWorkflow(plan: PipelinePlan): string {
  return `# DevSecOps workflow for the food catalog, generated by src/pipeline.ts.
# Pull requests never build or push images; triggers stay on the default branch.
name: devsecops

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run gate
      - run: npm audit --audit-level=${plan.auditLevel}

  sast:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run check

  image-scan:
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: '1'

  build:
    needs: image-scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${plan.image}
`;
}

export function renderCheatSheet(plan: PipelinePlan): string {
  return `# Release cheat sheet

The image tag is ${plan.image}; a CI build pushes it only after quality, SAST
and the Trivy filesystem scan all pass.

1. Open a pull request: quality, SAST and image-scan run, nothing is pushed.
2. Merge to main: the build job pushes the image to the registry.
3. Promote to production behind an environment-gated stage (see p06/p10 for
   the approval pattern).
`;
}