import type { DotnetModel } from "./model.ts";

export function renderPipeline(model: DotnetModel): string {
  const sdk = `${model.framework}.x`;
  const environments = model.environments.join(" ");
  return `# Azure DevOps pipeline generated by src/pipeline.ts for the .NET build
# and release plan. No secrets live here: the service connection and the App
# Service name arrive through pipeline variables.
trigger:
  branches:
    include:
      - ${model.mainBranch}
  paths:
    include:
      - 'src/**'
      - 'tests/**'

variables:
  Azure.ServiceConnection: ''
  Azure.AppServiceName: ''
  BuildConfiguration: Release

stages:
  - stage: Build
    displayName: Build and test
    jobs:
      - job: Build
        pool: ubuntu-latest
        steps:
          - checkout: self
          - task: UseDotNet@2
            displayName: Select .NET SDK
            inputs:
              packageType: sdk
              version: '${sdk}'
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - script: dotnet restore ${model.solutionPath} --nologo
            displayName: Restore
          - script: dotnet build ${model.projectPath} --configuration $(BuildConfiguration) --no-restore --nologo
            displayName: Build
          - script: dotnet test ${model.testProjectPath} --configuration $(BuildConfiguration) --no-build --logger "trx;LogFileName=results.trx" --results-directory $(Agent.TempDirectory)/trx --nologo
            displayName: Run tests
          - task: PublishTestResults@2
            displayName: Publish test results
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: VSTest
              testResultsFiles: '**/*.trx'
              searchFolder: $(Agent.TempDirectory)/trx
          - script: dotnet publish ${model.projectPath} --configuration $(BuildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)/app --nologo
            displayName: Publish artifact
          - task: PublishPipelineArtifact@1
            displayName: Upload artifact
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)/app
              artifactName: app

  - stage: Release
    displayName: Release to App Service
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy release
        # The environment owns the approvals: gate the stage on a manual
        # check in Azure DevOps, scoped to the main branch.
        environment: ${environments}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: Download artifact
                  inputs:
                    artifactName: app
                    path: $(Pipeline.Workspace)/app
                - task: AzureWebApp@1
                  displayName: Deploy to $(Azure.AppServiceName)
                  inputs:
                    azureSubscription: $(Azure.ServiceConnection)
                    appType: webAppLinux
                    appName: $(Azure.AppServiceName)
                    package: $(Pipeline.Workspace)/app
`;
}

export function renderNotes(model: DotnetModel): string {
  return `# Release runbook: ${model.appServiceName}

Created from src/pipeline.ts as an operational cheat sheet. Values are read at
runtime from pipeline variables, never from the repository.

1. School the environment (${model.environments.join(", ")}) with a manual
   approval check in Pipelines > Environments, scoped to main.

2. Set the two variables before the first run:
   az pipelines variable create --name Azure.ServiceConnection --value '<name>' --org <org> --project <project>
   az pipelines variable create --name Azure.AppServiceName --value '${model.appServiceName}' --org <org> --project <project>

3. Trigger a release from the main branch:
   az pipelines run --branch main

4. Routing to other branches is blocked by the trigger include list; promote
   to another environment by switching the pipeline variable before a rerun.

5. Inspect a run:
   az pipelines runs list --top 10
   az pipelines runs show --id <run-id>
`;
}