import type { AksModel } from "./model.ts";

export function renderPipeline(model: AksModel): string {
  return `# Azure DevOps pipeline generated by src/pipeline.ts.
# It runs Terraform for the AKS cluster behind an approval gate.
#
# Requirements in the organization:
# - a service connection with Contributor rights on the subscription
#   (the service connection id is referenced via the variables below);
# - an environment named 'prod-approval' with at least one approval defined on it;
# - a variable group named 'terraform-aks' containing:
#     SSH_PUBLIC_KEY   (the public key content; mark it as secret in the group)
pr:
  branches:
    include: ['${model.mainBranch}']
trigger:
  branches:
    include: ['${model.mainBranch}']

variables:
  - group: terraform-aks

stages:
  - stage: validate
    displayName: Terraform plan (no apply)
    jobs:
      - job: tf
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: terraform -chdir=infra init -backend=false
            displayName: Terraform init (no backend)
          - script: terraform -chdir=infra validate
            displayName: Terraform validate
          - script: terraform -chdir=infra fmt -check
            displayName: Terraform fmt check

  - stage: plan
    displayName: Terraform plan
    dependsOn: validate
    jobs:
      - job: plan
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              terraform -chdir=infra init \\
                -backend-config="resource_group_name=rg-portfolio-state" \\
                -backend-config="storage_account_name=STATE_ACCOUNT_PLACEHOLDER"
            displayName: Terraform init with backend
          - script: |
              terraform -chdir=infra plan \\
                -var="ssh_public_key=$(SSH_PUBLIC_KEY)" \\
                -out=$(Pipeline.Workspace)/tfplan
            displayName: Terraform plan
          - publish: $(Pipeline.Workspace)/tfplan
            artifact: tfplan

  - stage: apply
    displayName: Terraform apply (gated)
    dependsOn: plan
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${model.mainBranch}'))
    environment: prod-approval
    jobs:
      - job: apply
        pool:
          vmImage: ubuntu-latest
        steps:
          - download: current
            artifact: tfplan
          - script: |
              terraform -chdir=infra apply \\
                -auto-approve $(Pipeline.Workspace)/tfplan
            displayName: Terraform apply
`;
}

export function renderCheatSheet(model: AksModel): string {
  return [
    `# AKS release practice`,
    ``,
    `1. Merge to ${model.mainBranch}; validate + plan stages run on every merge.`,
    `2. The apply stage only runs on main and only after a human approval in the`,
    `   'prod-approval' environment.`,
    `3. Credentials never appear in the pipeline: ssh_public_key is read from`,
    `   the 'terraform-aks' variable group at plan time and the service`,
    `   connection handles Azure authentication on the runner.`,
    `4. Keep STATE_ACCOUNT_PLACEHOLDER matching the backend block of`,
    `   renderTerraform output before enabling the remote backend.`,
  ].join("\n");
}