import type { AksModel } from "./model.ts";

export function renderTerraform(model: AksModel): string {
  const pool = model.nodePool;
  return `# AKS cluster scaffolding generated by src/terraform.ts.
# Replace SUBSCRIPTION_ID_PLACEHOLDER and variable lets below with real values.
# The ssh_public_key is passed in from the caller and is never stored in the plan files.

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
  backend "azurerm" {
    resource_group_name  = "rg-portfolio-state"
    storage_account_name = "STATE_ACCOUNT_PLACEHOLDER"
    container_name       = "tfstate"
    key                  = "aks/terraform.tfstate"
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "main" {
  name     = "${model.resourceGroup}"
  location = "${model.location}"
}

resource "azurerm_kubernetes_cluster" "main" {
  name                = "${model.clusterName}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  dns_prefix          = "${model.dnsPrefix}"

  kubernetes_version = "${model.kubernetesVersion}"

  network_profile {
    network_plugin = "${model.networkPlugin}"
  }

  default_node_pool {
    name       = "${pool.name}"
    vm_size    = "${pool.vmSize}"
    node_count = ${pool.minCount}

    enable_auto_scaling          = true
    min_count                    = ${pool.minCount}
    max_count                    = ${pool.maxCount}

    upgrade_settings {
      max_surge = "25%"
    }
  }

  identity {
    type = "SystemAssigned"
  }

  linux_profile {
    admin_username = "azureuser"
    ssh_key {
      key_data = var.ssh_public_key
    }
  }

  role_based_access_control_enabled = true
}

variable "ssh_public_key" {
  type        = string
  description = "SSH public key content for the AKS node admin user. Pass it from CI; never commit it."
}

output "cluster_name" {
  value = azurerm_kubernetes_cluster.main.name
}

output "kube_config_raw" {
  description = "raw kubeconfig of the AKS cluster; treat as a secret"
  value       = azurerm_kubernetes_cluster.main.kube_config_raw
  sensitive   = true
}
`;
}