import type { PlannedSubnet, Topology } from "./topology.ts";

export function renderTerraform(topology: Topology): string {
  const lines: string[] = [];

  lines.push(
    "# Generated by p02-aws-vpc-architecture. Apply only into a sandbox account.",
    "",
    'terraform {',
    "  required_providers {",
    '    aws = {',
    '      source  = "hashicorp/aws"',
    '      version = "~> 5.0"',
    "    }",
    "  }",
    "}",
    "",
  );

  lines.push(
    `resource "aws_vpc" "main" {`,
    `  cidr_block           = "${topology.cidr}"`,
    "  enable_dns_support   = true",
    "  enable_dns_hostnames = true",
    "",
    "  tags = {",
    `    Name = "${topology.name}"`,
    "  }",
    "}",
    "",
  );

  for (const subnet of topology.subnets) {
    lines.push(
      `resource "aws_subnet" "${resourceName(subnet)}" {`,
      "  vpc_id                  = aws_vpc.main.id",
      `  cidr_block              = "${subnet.cidr}"`,
      `  availability_zone       = "${topology.region}${subnet.az}"`,
      `  map_public_ip_on_launch = ${subnet.tier === "web" ? "true" : "false"}`,
      "",
      "  tags = {",
      `    Name = "${topology.name}-${subnet.tier}-${subnet.az}"`,
      `    Tier = "${subnet.tier}"`,
      "  }",
      "}",
      "",
    );
  }

  lines.push(
    `resource "aws_internet_gateway" "main" {`,
    "  vpc_id = aws_vpc.main.id",
    "}",
    "",
  );

  for (const rt of topology.routeTables.private) {
    lines.push(
      `resource "aws_eip" "nat_${rt.az}" {`,
      '  domain   = "vpc"',
      "}",
      "",
      `resource "aws_nat_gateway" "nat_${rt.az}" {`,
      `  allocation_id = aws_eip.nat_${rt.az}.id`,
      `  subnet_id     = aws_subnet.web_${rt.az}.id`,
      "}",
      "",
    );
  }

  for (const rt of topology.routeTables.public) {
    lines.push(
      `resource "aws_route_table" "public_${rt.az}" {`,
      "  vpc_id = aws_vpc.main.id",
      "",
      "  route {",
      '    cidr_block = "0.0.0.0/0"',
      "    gateway_id = aws_internet_gateway.main.id",
      "  }",
      "}",
      "",
    );
  }

  for (const rt of topology.routeTables.private) {
    lines.push(
      `resource "aws_route_table" "private_${rt.az}" {`,
      "  vpc_id = aws_vpc.main.id",
      "",
      "  route {",
      '    cidr_block     = "0.0.0.0/0"',
      `    nat_gateway_id = aws_nat_gateway.nat_${rt.az}.id`,
      "  }",
      "}",
      "",
    );
  }

  for (const subnet of topology.subnets) {
    const routeTable = subnet.tier === "web" ? "public" : "private";
    lines.push(
      `resource "aws_route_table_association" "${resourceName(subnet)}" {`,
      `  subnet_id      = aws_subnet.${resourceName(subnet)}.id`,
      `  route_table_id = aws_route_table.${routeTable}_${subnet.az}.id`,
      "}",
      "",
    );
  }

  lines.push(
    'output "web_subnets" {',
    "  value = {",
    ...topology.subnets
      .filter((s) => s.tier === "web")
      .map((s) => `    "${s.az}" = aws_subnet.${resourceName(s)}.id`),
    "  }",
    "}",
    "",
  );

  return lines.join("\n").trimEnd() + "\n";
}

function resourceName(subnet: PlannedSubnet): string {
  return `${subnet.tier}_${subnet.az}`;
}